
- name: Add flocker repo
  lineinfile:
      dest: "/etc/apt/sources.list"
      state: present
      line: "deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/14.04/$(ARCH) /"
  tags:
    - flocker_repo

- name: Install flocker node
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
    force: yes
  with_items:
    - clusterhq-flocker-node
    - clusterhq-flocker-docker-plugin
    - clusterhq-flocker-cli
  tags:
    - flocker_install

- name: Create flocker certificate path
  file:
    path: /etc/flocker
    state: directory
    mode: 0700
  tags:
    - flocker_certificates
