#- name: Set flocker certificates on agents
#  synchronize:
#    mode: push
#    src: "/etc/flocker/{{ item.src }}"
#    dest: "/etc/flocker/{{ item.dest }}"
#    rsync_opts: "--rsh 'ssh -i /home/{{ main_user }}/.ssh/id_rsa'"
#    rsync_path: "sudo rsync"
#
#  with_items:
#    - { src: "control-{{ inventory_hostname }}.crt", dest: "control-service.crt" }
#    - { src: "control-{{ inventory_hostname }}.key", dest: "control-service.key" }
#    - { src: "cluster.crt", dest: "cluster.crt"}
#  delegate_to: "{{ master_node }}"
#  tags:
#    - flocker_certificates
#    - flocker_control_certificate
#    - sync
#

#- name: Check node authentication certificates present
#  stat: path=/etc/flocker/{{ item }}
#  register: auth_certs
#  with_items:
#    - node.crt
#    - node.key
#  tags:
#    - flocker_certificates
#    - flocker_authentication_certificate

# Small hack because synchronize doesn't work well...
- name: Create flocker node authentication certificates
  command: "flocker-ca create-node-certificate"
  args:
    chdir: /etc/flocker
  register: flocker_auth_cert
  delegate_to: "{{ master_node }}"
#  when: "not auth_certs.results.0.stat.exists or not auth_certs.results.1.stat.exists"
  tags:
    - flocker_certificates
    - flocker_authentication_certificate

- name: Get flocker node authentication certificates
  command: cat "/etc/flocker/{{ item }}"
  register: "flocker_auth_cert_body"
  delegate_to: "{{ master_node }}"
  with_items:
    - "{{ flocker_auth_cert.stdout | regex_replace('.*([a-f0-9-]{36})\\.crt.*', '\\1') }}.crt"
    - "{{ flocker_auth_cert.stdout | regex_replace('.*([a-f0-9-]{36})\\.crt.*', '\\1') }}.key"
  tags:
    - flocker_certificates
    - flocker_authentication_certificate

- name: Set flocker node authentication certificates on nodes
  copy:
    content: "{{ item.stdout }}"
    dest: "/etc/flocker/{{ item.item }}"
    owner: root
    group: root
    mode: 0600
  with_items: "{{ flocker_auth_cert_body.results }}"
  tags:
    - flocker_certificates
    - flocker_authentication_certificate

- name: Set correct name flocker node authentication certificates
  command: "mv {{ item.src }} {{ item.dest }}"
  args:
    chdir: /etc/flocker
    #creates: "{{ item.dest }}"
  with_items:
    - {
        src: "{{ flocker_auth_cert.stdout | regex_replace('.*([a-f0-9-]{36})\\.crt.*', '\\1') }}.crt",
        dest: "node.crt"
    }
    - {
        src: "{{ flocker_auth_cert.stdout | regex_replace('.*([a-f0-9-]{36})\\.crt.*', '\\1') }}.key",
        dest: "node.key"
    }

  tags:
    - flocker_certificates
    - flocker_authentication_certificate
