

- name: Start swarm master
  docker:
    name: swarm-manager
    command: manage consul://{{ consul_node }}:{{ service_discovery_port }}/swarm
    image: swarm
    state: reloaded
    hostname: swarm-manager
    ports:
      - "{{ docker_master_manage_port }}:2375"
  tags:
    - master
    - swarm
