---

- name: Set up authentication & authorization
  hosts: all
  sudo: True
  vars:
    remote_user: "{{ first_remote_user }}"
    ansible_ssh_user: "{{ first_ansible_ssh_user }}"
    ansible_ssh_private_key_file: "{{ first_ansible_ssh_private_key_file }}"

  roles:
    - auth
  tags:
    - all
    - auth
    - pre

- name: Install Docker
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - docker
  tags:
    - all
    - docker
    - pre

- name: Install master
  hosts: master
  sudo: True
  gather_facts: False
  roles:
    - service-discovery
#    - swarm-master
  tags:
    - master
    - swarm
    - service-discovery
