---

- name: Set up authentication & authorization
  hosts: all
  sudo: True
  gather_facts: False
  vars:
    remote_user: "{{ first_remote_user }}"
    ansible_ssh_user: "{{ first_ansible_ssh_user }}"
    ansible_ssh_private_key_file: "{{ first_ansible_ssh_private_key_file }}"

  roles:
    - auth
  tags:
    - all
    - auth
    - pre

- name: Install the dependencies
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - dependencies
  tags:
    - all
    - dependencies
    - pre

- name: Install Docker
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - docker-install
  tags:
    - all
    - docker
    - pre

- name: Install Flocker
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - flocker-install
  tags:
    - all
    - flocker
    - pre

- name: Setup master
  hosts: master
  sudo: True
  gather_facts: True
  roles:
    - service-discovery
    - swarm-master
  tags:
    - master
    - manager

- name: Setup nodes
  hosts: nodes
  sudo: True
  gather_facts: True
  roles:
    - swarm-agent
  tags:
    - node
    - agent
