# TODO: Refactor: {{ hostvars[inventory_hostname]['ansible_ssh_host'] }}
- name: Start swarm agent
  docker:
    name: swarm-agent
    command: >
        join
        --addr={{ hostvars[inventory_hostname]['ansible_ssh_host'] }}:{{ docker_manage_port }}
        consul://{{ consul_node }}:{{ service_discovery_port }}/swarm
    image: swarm
    state: reloaded
    hostname: swarm-agent
  tags:
    - master
    - swarm
