
- name: Create flocker cluster certificates
  command: "flocker-ca initialize {{ flocker_cluster_name }}"
  args:
    chdir: /etc/flocker
    creates:  "cluster.key"

  tags:
    - flocker_certificates
    - flocker_cluster_certificate

- name: Create flocker control certificate
  command: "flocker-ca create-control-certificate {{ master_node }}"
  args:
    chdir: /etc/flocker
    creates:  "control-{{ master_node }}.key"

  tags:
    - flocker_certificates
    - flocker_control_certificate

- name: Rename flocker control certificate
  command: "mv {{ item.src }} {{ item.dest }}"
  args:
    chdir: /etc/flocker
    creates: "{{ item.dest }}"
  with_items:
    - { src: "control-{{ master_node }}.crt", dest: "control-service.crt" }
    - { src: "control-{{ master_node }}.key", dest: "control-service.key" }
  tags:
    - flocker_certificates
    - flocker_control_certificate

- name: Set correct permission to control certificate
  file:
    path: /etc/flocker/control-service.key
    mode: 0600
  tags:
    - flocker_certificates
    - flocker_control_certificate
