---


- name: Add docker offial repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
  tags:
    - docker_repo

- name: Add docker official repo key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  tags:
    - docker_repo

- name: Install docker
  apt:
    name: docker-engine
    update_cache: yes
    state: present
  tags:
    - docker_install

- name: Set Docker daemon options
  lineinfile:
      dest: "/etc/default/docker"
      state: present
      create: yes
      line: "DOCKER_OPTS=\"{{ docker_opts }}\""
      regexp: "#? *DOCKER_OPTS=.*"
  tags:
    - docker_opts
    - docker_daemon

- name: Enable and restart Docker daemon
  service:
    name: docker
    enabled: yes
    state: restarted

  tags:
    - restart
    - docker_daemon
