
- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  tags:
    - pip_install
    - dependency

- name: Install pip2
  apt:
    name: python-pip
    state: present
    update_cache: yes
  tags:
    - pip_install
    - dependency

- name: Install pip3 dependencies
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
    executable: pip3
  with_dict: "{{ common_pip3_dependencies }}"

  tags:
    - pip3
    - dependency

- name: Install pip2 dependencies
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
    executable: pip
  with_dict: "{{ common_pip2_dependencies }}"

  tags:
    - pip2
    - dependency
