
- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  tags:
    - pip_instsall

- name: Install docker tools
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
    executable: pip3
  with_dict: "{{ common_pip_dependencies }}"

  tags:
    - pip
    - dependency
